import { Server } from './types';

export const SERVERS: Server[] = [
    {
        id: 'hypixel-net',
        name: 'Hypixel Network',
        ip: 'mc.hypixel.net',
        description: 'Hypixel is the largest Minecraft server in the world, featuring dozens of custom minigames including SkyBlock, BedWars, SkyWars, Murder Mystery, and more! Join millions of other players today and experience the best custom features and constant updates.',
        shortDescription: 'The largest Minecraft minigame network featuring massive SkyBlock and BedWars.',
        icon: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=150&h=150',
        banner: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=1200&h=400',
        tags: ['Minigames', 'Skyblock', 'BedWars', 'Economy', 'Custom Items'],
        version: '1.8 - 1.20',
        players: { online: 35420, max: 100000 },
        votes: 125430,
        uptime: 99.9,
        featured: true,
        region: 'NA',
        gamemodes: ['Minigames', 'Skyblock'],
        isPremium: true,
        createdAt: '2013-04-13T00:00:00Z'
    },
    {
        id: 'wynncraft',
        name: 'Wynncraft',
        ip: 'play.wynncraft.com',
        description: 'Wynncraft is the largest MMORPG server in Minecraft. A free to play game that requires no mods to play. Experience a vast custom world, classes, quests, guilds, and epic boss fights completely vanilla.',
        shortDescription: 'The largest MMORPG in Minecraft. Classes, quests, spells, and a massive custom world.',
        icon: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&q=80&w=150&h=150',
        banner: 'https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?auto=format&fit=crop&q=80&w=1200&h=400',
        tags: ['RPG', 'MMO', 'Quests', 'PvE', 'Custom Map'],
        version: '1.20+',
        players: { online: 1250, max: 4000 },
        votes: 45200,
        uptime: 99.8,
        featured: true,
        region: 'NA',
        gamemodes: ['RPG', 'Survival'],
        isPremium: true,
        createdAt: '2013-02-14T00:00:00Z'
    },
    {
        id: 'complex-gaming',
        name: 'Complex Gaming',
        ip: 'hub.mc-complex.com',
        description: 'Complex Gaming is a network offering multiple game modes from Pixelmon, Skyblock, Factions, Prison, Creative, and Survival! We have something for everyone. Friendly community and active staff.',
        shortDescription: 'Active multi-server featuring Pixelmon, Factions, Prison, and Skyblock.',
        icon: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&q=80&w=150&h=150',
        banner: 'https://images.unsplash.com/photo-1580234811497-9df7fd2f357e?auto=format&fit=crop&q=80&w=1200&h=400',
        tags: ['Pixelmon', 'Skyblock', 'Factions', 'Prison', 'Vanilla'],
        version: '1.12.2 - 1.20',
        players: { online: 4500, max: 10000 },
        votes: 38900,
        uptime: 99.9,
        featured: false,
        region: 'NA',
        gamemodes: ['Pixelmon', 'Factions', 'Prison', 'Skyblock'],
        isPremium: false,
        createdAt: '2018-05-10T00:00:00Z'
    },
    {
        id: 'mcc-island',
        name: 'MCC Island',
        ip: 'play.mccisland.net',
        description: 'The official public server for the MC Championship. Play your favorite MCC games like Hole in the Wall, Battle Box, Sky Battle, and TGTTOSAWAF! Form parties with friends and climb the leaderboards.',
        shortDescription: 'Official public server for MC Championship minigames.',
        icon: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=150&h=150',
        banner: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&q=80&w=1200&h=400',
        tags: ['Minigames', 'PvP', 'Parkour', 'Competitive'],
        version: '1.20.4',
        players: { online: 2100, max: 5000 },
        votes: 21500,
        uptime: 99.5,
        featured: true,
        region: 'EU',
        gamemodes: ['Minigames', 'PvP'],
        isPremium: true,
        createdAt: '2022-08-20T00:00:00Z'
    },
    {
        id: 'lemoncloud',
        name: 'LemonCloud',
        ip: 'play.lemoncloud.net',
        description: 'LemonCloud is an awesome network featuring OP Prison, OP Factions, Skyblock, Survival, and Creative! A vibrant community with regular events, custom enchants, and dedicated staff.',
        shortDescription: 'Awesome network with OP Prison, Factions, Skyblock, and Survival.',
        icon: 'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&q=80&w=150&h=150',
        banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=1200&h=400',
        tags: ['OP Prison', 'Factions', 'Skyblock', 'Economy', 'Custom Enchants'],
        version: '1.8.8 - 1.20',
        players: { online: 850, max: 2000 },
        votes: 15400,
        uptime: 99.7,
        featured: false,
        region: 'NA',
        gamemodes: ['Prison', 'Factions', 'Skyblock'],
        isPremium: false,
        createdAt: '2015-01-01T00:00:00Z'
    },
    {
        id: '2b2t',
        name: '2b2t',
        ip: '2b2t.org',
        description: 'The oldest anarchy server in Minecraft. No rules, no resets, hvh. Survive in a chaotic world shaped entirely by players over more than a decade.',
        shortDescription: 'The oldest anarchy server in Minecraft. No rules, no resets.',
        icon: 'https://images.unsplash.com/photo-1506501139174-099022df5260?auto=format&fit=crop&q=80&w=150&h=150',
        banner: 'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&q=80&w=1200&h=400',
        tags: ['Anarchy', 'Survival', 'Vanilla', 'PvP', 'No Rules'],
        version: '1.19.4',
        players: { online: 600, max: 2000 },
        votes: 10200,
        uptime: 98.0,
        featured: false,
        region: 'NA',
        gamemodes: ['Anarchy', 'Survival'],
        isPremium: false,
        createdAt: '2010-12-01T00:00:00Z'
    }
];
